# Generated by Django 3.1.3 on 2020-11-20 14:02

import app.models
from django.db import migrations
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201119_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hero',
            field=stdimage.models.StdImageField(default=django.utils.timezone.now, upload_to=app.models.get_file_path, verbose_name='Hero'),
            preserve_default=False,
        ),
    ]
